sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 6
matrix:
  fast_finish: true
env:
  global:
    - BUILD_LEADER_ID=2
script: npm run travis
before_install:
  - npm i -g npm
before_script:
  - npm prune
branches:
  only:
  - master
