version: '2'
services:
  geotrans:
    build:
      context: '.'
      dockerfile: Dockerfile
    # if mounting volumes don't forget that you may need to reinstall the node_modules and the node-gyp binding.
#    volumes:
#      - ./:/opt/mgrs
    command: npm start
    ports:
      - "3000:3000"
    environment:
      port: 3000